services:
  watermark-api:
    build: .
    container_name: watermark-api
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8100:8100"
    volumes:
      - ./app/assets/fonts:/app/app/assets/fonts:ro
    environment:
      - TZ=UTC
networks:
  app-network:
    external: true
